<a href="https://colab.research.google.com/github/SJGE100720/Intro_Phyton_Conline/blob/main/D%C3%ADa_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tema 11

In [4]:
import numpy as np #"as" le damos el nombre np a la librería, un sobrenombre
a = [1,2,3]
print(type(a))
print(3 * a)
print(a+a)
a = np.array(a)
print(type(a))
print(3 * a)
print(a+a)

<class 'list'>
[1, 2, 3, 1, 2, 3, 1, 2, 3]
[1, 2, 3, 1, 2, 3]
<class 'numpy.ndarray'>
[3 6 9]
[2 4 6]


In [7]:
#Numpy genera vectores
#Diez = [1,2,3,4,5,6,7,8,9,10] Escribir arreglos más largos sería
#tedioso, entonces:
Diez = np.linspace(1,10,10) #(origen, final, cuántos elementos contendrá)
print(Diez)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [8]:
ceros = np.zeros(3)
print(ceros)

[0. 0. 0.]


In [11]:
b = np.array([-1,-60,12,3.5,2,3,3])
Min = np.amin(b)
print(Min)
Max = np.amax(b)
print(Max)  
Donde_3_5 = np.where(b == 3.5)
print(Donde_3_5)
Donde_3 = np.where(b == 3)
print(Donde_3)

-60.0
12.0
(array([3]),)
(array([5, 6]),)


In [17]:
#x^2 - 3x + 2 = 0
Ecu_1 = np.array([1,-3,2])
Sol_1 = np.roots(Ecu_1)
print(Sol_1)
#4x^4 - 2x^2 +3x - 2 = 0
Ecu_2 = np.array([4,0,-2,3,-2])
Sol_2 = np.roots(Ecu_2)
print(Sol_2)

[2. 1.]
[-1.20921113+0.j          0.26185021+0.73117971j  0.26185021-0.73117971j
  0.6855107 +0.j        ]


In [26]:
#5x - 3y - z = 1
#x + 4y - 6z = -1
#2x + 3y + 4z = 9
X = np.array([[5,-3,-1],[1,4,-6],[2,3,4]])
Val = np.array([1,-1,9])
print(X)
print("---------")
print(Val)
print("---------")
print("Solución")
Sol_S = np.linalg.solve(X,Val) #linalg es un método de álgebra lineal
print(Sol_S)

[[ 5 -3 -1]
 [ 1  4 -6]
 [ 2  3  4]]
---------
[ 1 -1  9]
---------
Solución
[1. 1. 1.]


In [29]:
Y = np.array([[3,-2,-6],[7,8,-6],[2,1,4]])
#print(Y)
XY = np.matmul(X,Y)
print(XY)

[[ -8 -35 -16]
 [ 19  24 -54]
 [ 35  24 -14]]
