<a href="https://colab.research.google.com/github/SJGE100720/Intro_Phyton_Conline/blob/main/D%C3%ADa_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Día 3
Tema_5

In [ ]:
#índices en listas
A = [89, 2, 3, 4, 5]
print(A)

[89, 2, 3, 4, 5]


In [ ]:
A[0] = 1 #Esta línea cambia la posición 0 por el valor 1
print(A)
A[4] = 100
print(A)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 100]


#Podemos añadir elementos a listas

In [ ]:
 B = [1,2,3]
 print(B)
 B.append(4) #Se le agrega el número al final
 B #También sirve para imprimir, pero sólo aquí

[1, 2, 3]


[1, 2, 3, 4]

In [ ]:
C = []
C 
C.append([1,2,3])
C

[[1, 2, 3]]

In [ ]:
C.append([4,5,6])
C.append([7,8,9])
C

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
import numpy as np
C = np.array(C) #Matriz de 3x3
C

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#Operaciones a listas

In [ ]:
print(C[0])#Imprime la posición que indiques del vector
print(C[1])
print(C[1][0]) #Dentro del vector, cierta posición

[1 2 3]
[4 5 6]
4


In [ ]:
D = [1,2,3,4,5,6,7,8,9,10]
D 

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
Suma = sum(D) #Suma los elementos del vector
print(Suma)

55


In [ ]:
Longitud = len(D) #Cantidad de elementos del vector, "longitud"
print(Longitud)

10


In [ ]:
Promedio = sum(D)/Longitud
print(Promedio)

5.5


In [ ]:
#Otra forma de calcular el promedio
import statistics as st
Promedio_2 = st.mean(D) #Statistics: st.nombre
Promedio_2
#Se puede colocar solamente "import statistics" para llamar la librería y en el 
#comando, anotar el nombre completo como "statistics.mean"


5.5

#Listas con string

In [ ]:
Strings = ['abc','dfg','ghi','jkl']
print(Strings[0][2])

c


In [ ]:
Longitud = len(Strings)
Longitud

4

In [ ]:
print(Strings[0:2])
print(Strings[2][0:2]) #vector 2 dentro del string, de la posición 0 
#hasta antes de la 2. *Recordar que comienza en 0 la enumeración.

['abc', 'dfg']
gh


#Diccionarios

In [ ]:
Datos_alumno = {
    'Nombre': 'Octavio',
    'Apellido': 'Paz',
    'Matrícula': '123456',
    'Horario': 'Matutino',
    'Beca': 'Sí',
}
print(Datos_alumno['Matrícula'])
print(Datos_alumno['Apellido'])
print(Datos_alumno['Beca'])

123456
Paz
Sí


In [ ]:
#Agregamos más cosas al diccionario
Datos_alumno.update({'Materias':['Física', 'Química', 'Programación']})
Datos_alumno

{'Apellido': 'Paz',
 'Beca': 'Sí',
 'Horario': 'Matutino',
 'Materias': ['Física', 'Química', 'Programación'],
 'Matrícula': '123456',
 'Nombre': 'Octavio'}

In [ ]:
print(Datos_alumno['Materias'])
print(Datos_alumno['Materias'][0:2])

['Física', 'Química', 'Programación']
['Física', 'Química']


#Diccionarios anidados

In [ ]:
#Definimos diccionario con más datos
Pacientes = [
    {
     'Nombre':'Juan',
     'Seguro':'Si',
     'ID_seguro':'987654321',
     'Covid':'Si',
     'G_sanguineo':'AB+'
    },

    {
     'Nombre':'Maria',
     'Seguro':'Si',
     'ID_seguro':'123456789',
     'Covid':'No',
     'G_sanguineo':'A+'
    },

    {
     'Nombre':'Ernesto',
     'Seguro':'No',
     'ID_seguro':'N/A',
     'Covid':'No',
     'G_sanguineo':'B+',
    }
]

In [ ]:
Pacientes[0] #Imprime la posición 0 de la lista

{'Covid': 'Si',
 'G_sanguineo': 'AB+',
 'ID_seguro': '987654321',
 'Nombre': 'Juan',
 'Seguro': 'Si'}

In [ ]:
print(Pacientes[1]['Nombre'])
print(Pacientes[1]['Seguro'])
print(Pacientes[1]['ID_seguro'])

Maria
Si
123456789


In [ ]:
print(Pacientes[2]['Seguro'])
print(Pacientes[2]['Covid'])
print(Pacientes[2]['G_sanguineo'])

No
No
B+


In [ ]:
print(Pacientes[0]['G_sanguineo'][0:2])#se debe de tener cuidado,
#dependiendo del contexto, no deberías usar el comando [0:2]

AB


#Tarea
- Añadir diccionarios (mínimo 2).
- El programa solicite que teclees el valor de las variables.
- Luego estas se agreguen al diccionario con update.

In [2]:
Autos = [ #Diccionarios anidados vacíos
         {
             
         },
         {
             
         }
]
print("Por favor, introduzca los datos de dos diferentes automóviles\npara completar los diccionarios anidados:")
Marca_1 = input("Introduzca la marca del auto 1: ")
Placa_1 = input("Introduzca la placa: ")
Año_1 = input("Introduzca el año del auto: ")
Marca_2 = input("Introduzca la marca del auto 2: ")
Placa_2 = input("Introduzca la placa: ")
Año_2 = input("Introduzca el año del auto: ")

Autos[0].update({'Marca':Marca_1,'Placa':Placa_1,'Año':Año_1})
Autos[1].update({'Marca':Marca_2,'Placa':Placa_2,'Año':Año_2})
Autos

Por favor, introduzca los datos de dos diferentes automóviles
para completar los diccionarios anidados:
Introduzca la marca del auto 1: Nissan
Introduzca la placa: AGS562
Introduzca el año del auto: 2011
Introduzca la marca del auto 2: Toyota
Introduzca la placa: AGS100
Introduzca el año del auto: 2017


[{'Año': '2011', 'Marca': 'Nissan', 'Placa': 'AGS562'},
 {'Año': '2017', 'Marca': 'Toyota', 'Placa': 'AGS100'}]